# Generated by Django 5.0.6 on 2024-06-04 14:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_user_receive_alerts'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='receive_alerts',
            field=models.BooleanField(default=False),
        ),
    ]
